version: '3'
services:
    mongo:
        image: mongo:6.0
        ports:
            - 27017:27017
        networks:
            dome:
        volumes:
            - ./proxy-data:/data/db

    proxy:
        image: proxy-dev
        links:
            - mongo
        depends_on:
            - mongo
        ports:
            - 8004:8004
        networks:
            dome:
                aliases:
                    - proxy.docker
        environment:
            - BAE_LP_SIOP_ENABLED=false
            - BAE_LP_SIOP_CLIENT_ID=marketplace-client
            - BAE_LP_SIOP_VERIFIER_HOST=https://verifier.dome-marketplace.org
            - BAE_LP_SIOP_VERIFIER_QRCODE_PATH=/api/v1/loginQR
            - BAE_LP_SIOP_VERIFIER_TOKEN_PATH=/token
            - BAE_LP_SIOP_VERIFIER_JWKS_PATH=/.well-known/jwks
            - BAE_LP_SIOP_CALLBACK_PATH=http://proxy.docker:8004/auth/vc/callback
            - BAE_LP_SIOP_ALLOWED_ROLES=seller,customer
            - BAE_LP_DOME_TRUST=https://dome-certification.dome-marketplace-sbx.org
            - BAE_LP_KNOWLEDGE_BASE_URL=https://knowledgebase.dome-marketplace-sbx.org
        volumes:
            - ../:/business-ecosystem-logic-proxy

networks:
    dome:
        external: true
